---

- hosts: localhost
  become: true
  tasks:

  - name: update repository index
    apt:
            update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

    # when ansible_distribution_version == "8.2"
    # when ansible_distribution == "Centos" and ansible_distribution_version == "8.2"

  - name: install apache2 package in Ubuntu
    apt:
            name: apache2
            state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache in Ubuntu
    apt:
            name: libapache2-mod-php
            state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
            update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package in Centos
    dnf:
            name: httpd
            state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache in Centos
    dnf:
            name: php
            state: latest
    when: ansible_distribution == "CentOS"
